title: My Personal Website
description: My Journey, Piano Performances, Competitions, and Blog
author: Kiki
url: "https://demisemihope.github.io"
baseurl: ""
theme: beautiful-jekyll
markdown: kramdown
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
