title: "My Personal Website"
description: "University Application Journey, Piano Performances, Competitions, and Blog"
author: "Your Name"
url: "https://demisemihope.github.io"
baseurl: ""
theme: "beautiful-jekyll"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
